name: Build & Test

on: [push, workflow_dispatch]

jobs:
  build_flatpak:
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: icloud-for-linux.flatpak
        manifest-path: flatpak/io.github.crossplatform.icloud-for-linux.yml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Upload Flatpak Artifact
      uses: actions/upload-artifact@v4
      with:
        name: flatpak
        path: icloud-for-linux.flatpak
